image: ghcr.io/olix0r/tcp-echo:v14

reverse: false

client:
  replicas: 1
  concurrency: 2000
  messagesPerConnection: 100000
  linkerdInject: false

server:
  services: 1
  replicas: 1
  linkerdInject: true
  opaque: false

linkerd: {}
  #proxyImage: ...
  #proxyVersion: ...
