apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tcp-echo
    role: client
  name: client
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: tcp-echo
      role: client
  replicas: {{ int .Values.client.replicas }}
  template:
    metadata:
      labels:
        app: tcp-echo
        role: client
      annotations:
        linkerd.io/inject: {{.Values.client.linkerdInject | default false | ternary "enabled" "disabled" }}
        {{- if .Values.linkerd.proxyImage }}
        config.linkerd.io/proxy-image: {{ .Values.linkerd.proxyImage }}
        {{- end }}
        {{- if .Values.linkerd.proxyVersion }}
        config.linkerd.io/proxy-version: {{ .Values.linkerd.proxyVersion }}
        {{- end }}
    spec:
      containers:
        - name: main
          image: {{ .Values.image }}
          env:
            - name: RUST_LOG
              value: debug
          args:
            - client
            - --concurrency={{.Values.client.concurrency | default 1}}
            {{- if .Values.reverse }}
            - --reverse
            {{- end }}
            {{- range $i, $e := until (.Values.server.services | int) }}
            - {{printf "tcp://echo-%03d:4444" $i}}
            {{- end }}

